# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_b <- function(x, base) {
    .Call('_NZMastersample_log_b', PACKAGE = 'NZMastersample', x, base)
}

HaltonSeq <- function(k, base, n) {
    .Call('_NZMastersample_HaltonSeq', PACKAGE = 'NZMastersample', k, base, n)
}

GetBoxIndices <- function(lxy, base, J) {
    .Call('_NZMastersample_GetBoxIndices', PACKAGE = 'NZMastersample', lxy, base, J)
}

SolveCongruence <- function(A, base, J) {
    .Call('_NZMastersample_SolveCongruence', PACKAGE = 'NZMastersample', A, base, J)
}

SolveCongruence2 <- function(A, base, J) {
    .Call('_NZMastersample_SolveCongruence2', PACKAGE = 'NZMastersample', A, base, J)
}

